name = "pb"
compatibility_date = "2024-12-19"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "shz.al"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "99c068016f5845ea926f11ff6749a0dc"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://tf.281000.xyz"

# url to repo, displayed in the index page
REPO = "https://github.com/dvlin-dev/file-worker"

# url to the favicon
FAVICON = "https://sharzy.in/favicon-32x32.png"

# the name displayed in TOS
TOS_MAINTAINER = "dvlin"

# the email displayed in TOS
TOS_MAIL = "dvlin.dev@gmail.com"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
